security:
    firewalls:

        main:
                pattern:    ^/
                anonymous: true

                form_login:
                        login_path:  /login
                        check_path:  /login_check
                        default_target_path: /
                logout:
                        path:   /logout
                        target: /


    providers:
        users:
            entity: { class: AppBundle:User, property: username }

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/cart, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/user, roles: ROLE_USER }

    encoders:
        AppBundle\Entity\User:
            algorithm: sha512
